### PR TITLE
Use the web renderer

### LINKED ISSUE #71: no way to filter and ctrl+f does not work
I wanted to quickly find pc-kernel snap.

There is no filter to type `pc-kernel` to filter everything by pc-kernel.

I instead pressed `ctrl+f` and tried to search for pc-kernel, but somehow that doesn't work, as it brings up nothing.

### PR DESCRIPTION
**Pull request by mz2**
Use the web renderer so that for example finding text works.

Fixes https://github.com/canonical/test_observer/issues/71

### CODE REVIEW

**Review by omar-selo — APPROVED** [review]
This is a very slight improvement. Namely, while ctrl+f works with this change, I found two limitations:
1. The search string can't have any special characters. (i.e. ' ', '_', ':', etc.) as it wouldn't work if it does
2. It can't find anything outside the view. So for instance if you need to scroll to find an artefact, then ctrl+f will not find it

These are very big limitations, specifically 2 would kind of render this useless. But I don't see an issue right now with making this change anyways.

**Comment by nadzyah** [comment]
@omar-selo @mz2 shall we merge this PR?

**Comment by omar-selo** [comment]
My concern is that html web renderer is [less performant](https://docs.flutter.dev/platform-integration/web/renderers#choosing-which-option-to-use). Given that it can't find text outside the field of view it's not adding much value. So if performance is an issue (as we can see now). Perhaps it's better not to merge this

**Comment by omar-selo** [comment]
This is probably no longer needed given that we've added a [search box](https://github.com/canonical/test_observer/pull/122). So the underlying issue of finding is fixed

**Pull request closed without merging**
